---
title: "simulation results"
author: "Julia Wrobel"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
hitheme: tomorrow
highlighter: highlight.js
---

# Overview

This file loads data objects stored from simulations and produces figures for the paper. Libraries and code are sourced below. 

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(viridis)
library(spatstat.random)
library(patchwork)
library(latex2exp)

knitr::opts_chunk$set(echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 9,
  fig.height = 4,
  fig.path = '../output/'
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

my_colors <- c(
  "K" = "#440154",
  "Kinhom" = "#414487",
  "perm" = "#2A788E",
  "perm approx" = "#22A884",
  "KAMP" = "#7AD151",
  "KAMP lite" = "#FDE725"
)
```

# Source code

Source file for consolidating simulations

```{r}
source(here::here("source", "utils.R"))
```


# Variance

```{r}
files = list.files(here::here("output", "bivariate_variance"),
                   full.names =  TRUE, recursive = TRUE, pattern = ".RDA")

df = map_dfr(files, merge_files, variance = TRUE)
```



Data cleaning

```{r}

df = df %>%
  filter(r != 0) %>%
  mutate(method = factor(method, levels = c("kperm", "kperm approx", "kamp", "kamplite"),
                         labels = c("perm", "perm approx", "KAMP", "KAMP lite"))) %>%
  filter(method != "perm approx")
  
```




```{r}

df %>%
  filter(type %in% c("hom", "homClust"), abundance > 0.01) %>%
  group_by(abundance, lambda_n, type, r) %>%
  summarize(n = mean(n),
            m1 = mean(m1),
            m2 = mean(m2)) %>%
  ungroup() %>% print(n = 100)
```



## Power/Type I error

First look at scenarios with no true clustering. Calculating P(reject Ho|Ho True)



```{r}
df_type1 = df %>%
  filter(type %in% c("hom", "inhom"),
         ) %>%
  group_by(r, type, method, lambda_n, abundance) %>%
  summarize(type1_error = sum(pvalue<= 0.05)/n(),
            n_sim = n()) %>%
  ungroup()


type1 = df_type1 %>%
  filter(r == .25, type == "hom") %>%
  mutate(abundance = factor(abundance),
         lambda_n = factor(lambda_n)) %>%
  ggplot(aes(lambda_n, type1_error, group = method,
             color = method, linetype = method)) +
  geom_point(size = 3) +
  scale_color_manual(values = my_colors) +
  geom_line(linewidth = 1.25) +
  labs(y = "Type 1 error", x = expression(lambda[n]),
       title = "Homogeneous") +
  ylim(0.03, 0.08) +
  geom_hline(yintercept = 0.05, linetype = 4) +
  theme(legend.position = "none") +
  facet_wrap(~abundance, ncol = 3, scales= "free_x", labeller = label_both)

type1_inhom = df_type1 %>%
  filter(r == .25, type == "inhom") %>%
  mutate(abundance = factor(abundance),
         lambda_n = factor(lambda_n)) %>%
  ggplot(aes(lambda_n, type1_error, group = method,
             color = method, linetype = method)) +
  geom_point(size = 3) +
  scale_color_manual(values = my_colors) +
  geom_line(linewidth = 1.25) +
  labs(y = "Type 1 error", x = expression(lambda[n]),
       title = "Inhomogeneous") +
  ylim(0.03, 0.08) +
  geom_hline(yintercept = 0.05, linetype = 4) +
  theme(legend.position = "none") +
  facet_wrap(~abundance, ncol = 3, scales= "free_x", labeller = label_both)

```




Power = P(reject Ho|H1 True)

```{r}
power_df = df %>%
    filter(type %in% c("homClust", "inhomClust"),
           r == 0.25
          ) %>%
  group_by(type, method, lambda_n, abundance) %>%
  summarize(power = sum(pvalue<= 0.05)/n(),
            n_sim = n()) %>%
  ungroup() %>%
    mutate(abundance = factor(abundance),
         lambda_n = factor(lambda_n))




power = power_df %>%
  filter(type == "homClust") %>%
  ggplot(aes(lambda_n, power, group = method,
             color = method, linetype = method)) +
  geom_point(size = 3) +
  scale_color_manual(values = my_colors) +
  geom_line(linewidth = 1.25) +
  labs(y = "Power", x = expression(lambda[n]),
       title = "Homogeneous + clustered") +
  ylim(0.05, 1) +
  geom_hline(yintercept = 0.9, linetype = 4) +
  theme(legend.position = c(0.6, 0.4), legend.title = element_blank()) +
  facet_wrap(~abundance, ncol = 3, scales= "free_x", labeller = label_both)

power_inhom = power_df %>%
  filter(type == "inhomClust") %>%
  ggplot(aes(lambda_n, power, group = method,
             color = method, linetype = method)) +
  geom_point(size = 3) +
  scale_color_manual(values = my_colors) +
  geom_line(linewidth = 1.25) +
  labs(y = "Power", x = expression(lambda[n]),
       title = "Inhomogeneous + clustered") +
  ylim(0.05, 1) +
  geom_hline(yintercept = 0.9, linetype = 4) +
  theme(legend.position = "none", legend.title = element_blank()) +
  facet_wrap(~abundance, ncol = 3, scales= "free_x", labeller = label_both)


```



```{r supp_power_biv, fig.height = 6}
(type1 + type1_inhom)/(power + power_inhom)
```





